apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-todo
  template:
    metadata:
      labels:
        app: fastapi-todo
    spec:
      containers:
      - name: fastapi-todo-app
        image: lukedoma/fastapi-todo-app:latest
        ports:
        - containerPort: 8000
